# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Firebase-Auth-Lab' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Firebase-Auth-Lab
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'

  target 'Firebase-Auth-LabTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
